### ISSUE TITLE
Where UE4 ?

### ISSUE THREAD

**Issue by SpodoY** [mstrommer/ALDA_Exercise3v12021#1]
![UE04?](https://user-images.githubusercontent.com/72346498/168992799-861d6e66-3586-413b-90ba-e557d95675b4.jpg)

**Comment by mstrommer** [comment]
![6i13on](https://user-images.githubusercontent.com/69633126/171061515-0c0b420a-a961-467b-ad89-669cf9bfb4bc.jpg)
